Ext.define('CS.schede.schede.noppain.NoppainStore', {
	extend: 'Ext.data.Store',
	fields: [
		{name:'id'},
		{name:'data',type:'date'},
		{name:'compilatore'},
		{name:'as'},
		{name:'ar'},
		{name:'bs'},
		{name:'br'},
		{name:'cs'},
		{name:'cr'},
		{name:'ds'},
		{name:'dr'},
		{name:'es'},
		{name:'er'},
		{name:'fs'},
		{name:'fr'},
		{name:'gs'},
		{name:'gr'},
		{name:'hs'},
		{name:'hr'},
		{name:'is'},
		{name:'ir'},
		{name:'ind1'},
		{name:'ind1int'},
		{name:'ind2'},
		{name:'ind2int'},
		{name:'ind3'},
		{name:'ind3int'},
		{name:'ind4'},
		{name:'ind4int'},
		{name:'ind5'},
		{name:'ind5int'},
		{name:'ind6'},
		{name:'ind6int'},
		{name:'senteDolore'},
		{name:'faccioMale'},
		{name:'progVisita'},
		{name:'stimaDolore'},
		{name:'posDoloreL'},
		{name:'posDoloreT'},
		{name:'posLesioneL'},
		{name:'posLesioneT'},
		{name:'mesiScadenza'},
		{name:'nonSomministrabile'},
		{name:'tot55'},
		{name:'idRicovero'},
		{name:'scadenza'},
		{name:'agenda'},
		{name:'convertito'},
		{name:'punteggioMassimo'},
		{name:'slider'},
		{name:'compilatoreNominativo'},
		{name:'compilatoreFigProf'}, 
		
	],
	proxy: {
		type: 'ajax',
		method:'GET',
		url: `${CbaRootServer}`+'/cba/css/cs/ws/skval/noppain/get',
		api: {
            read: `${CbaRootServer}`+'/cba/css/cs/ws/skval/noppain/get',
			create:`${CbaRootServer}`+'/cba/css/cs/ws/skval/noppain/new',
			update:`${CbaRootServer}`+'/cba/css/cs/ws/skval/noppain/update',
			destroy:`${CbaRootServer}`+'/cba/css/cs/ws/skval/noppain/delete'
        },
		reader: {
			type: 'json',
			messageProperty: 'message',
			rootProperty: 'data'
		}
	},	
	autoDestroy: true	
});